### ISSUE TITLE
Update Mavros to v0.18.x to get MAVLink 2 for logging with ULogger

### ISSUE THREAD

**Issue by mindThomas** [intel-aero/meta-intel-aero#127]
Due to the old version of Mavros supplied within the meta-ros layer one can not do any logging of the PX4 data using the Ulogger at the same time as running Mavros on the drone.
This limits any possibility in doing logging of automated drone behaviour through ROS, as this would require both Mavros and Ulog to run at the same time.

I have tried to do some of the changes in meta-ros myself, pulling in the latest MAVLink, but without any luck.
Instead I ran into problems with the message generator not generating proper C++ header files (common.hpp etc.) and after solving that the Python based message generator (mavgen.py) within pymavlink complained about missing the Python library, "future"

Hopefully anyone can point us in any usefull way?
Topic has also been posted here: https://github.com/bmwcarit/meta-ros/issues/489

Kind regards
Thomas Jespersen

**Comment by mbelluzzo** [comment]
As far I could check, even with 17.05 we are using mavlink 2.0 in terms of wired-protocol (mavros build properly detect this and sets -DMAVLINK2_COMPAT). Do I don't think the problem is because of the version of mavlink itself, but if is something else (or mavlink 2.0 is not about wired-protocol) can you share the commit on mavros that fix this issue so we can see what we can do if ppl on meta-ros does not update the recipe? Depending of what it is it may be possible to keep a workaround on our recipes.

**Comment by mhkabir** [comment]
@mbelluzzo I'm one of the developers of mavros. The current version of mavros + mavlink you ship does not have mavlink 2.0 support. It came in only in 0.18.0 : https://github.com/mavlink/mavros/releases/tag/0.18.0

Therefore our mavros proxy implementation cannot route Mavlink 2.0 packets and the ULog streaming does not work. You would also need to update the version of mavlink to the latest one to make sure that the message definitions are present.

Thanks!

**Comment by vooon** [comment]
And more specific: `MAVLINK2_COMPAT` do not enable v2 parsing, it is fix v1 API changes introduced with v2 release. So it allow to use fresh mavlink package with 0.17 version.
Routing of v2 only possible in 0.18 (Kinetic) and up. You should be able to build it on Indigo, but you need mavlink from Kinetic.

**Comment by lucasdemarchi** [comment]
@vooon mavlink and pymavlink, right (since now you are using C++11 generator)?

**Comment by vooon** [comment]
[mavlink-gbp-release](https://github.com/mavlink/mavlink-gbp-release) ship both. You may place `release/kinetic/mavlink` branch at workspace and do `catkin build`. CMake uses Python 2, so you need to install dependencies first. Most bugs come from `future` (setup.py imports pymavlink, it imports future and pip for some reason reads requirements.txt after setup).

**Comment by mindThomas** [comment]
But that would still not allow Mavros to be used together with flight logs being logged with ULogger.

**Comment by lucasdemarchi** [comment]
You would need to make ulogger to talk to mavros.

Or when we bump the version and figure out the problem of talking via TCP/UDP  you can put mavlink-router as the only one using ttyS1 since it has embedded ulog support.

**Comment by vooon** [comment]
Why? Mavros 0.18 should route v2 without a problem.
Except that mavros itself do not support packet signing, but routing may work (code for signature handling exists, untested).

**Comment by mindThomas** [comment]
> Why? Mavros 0.18 should route v2 without a problem.
Exactly. But that would require Mavros 0.18.
The version is 0.17.5 right now, so even by using `release/kinetic/mavlink` of https://github.com/mavlink/mavlink-gbp-release it wouldn't work.

**Comment by mbelluzzo** [comment]
I will work on bump mavros version all way to 0.18.7 and update
mavlink-gbp-release to use kinetic. If it happens that we just need to keep
some custom recipes while those are not bumped on meta-ros upstream, we
will do that. If not, I post here whatever is going wrong for ideas on what
can be done.

**Comment by mindThomas** [comment]
@mbelluzzo Fantastic. I will await your results and hopefully good news.
Any ETA? Are you working on this problem right now (at the moment) or is it a postponed task?

**Comment by mbelluzzo** [comment]
ros-mavlink is already compiling with kinetic version and worked my way to make yocto pick my mavros recipe (0.18.7). A mistaken priority setting was on the way but I fixed. Now I need to properly update my 0.18.7 recipes with the correct checksums etc and hope for the best during compiling, but this will tomorrows task cause I have to leave.

**Comment by mbelluzzo** [comment]
Is working, going to send pull requests in a few :-)

rostopic echo /mavros/imu/data
```
---
header: 
  seq: 1186
  stamp: 
    secs: 1493406149
    nsecs: 560807872
  frame_id: fcu
orientation: 
  x: 0.0197534165702
  y: 0.000656454287714
  z: -0.720316937721
  w: -0.693363551312
orientation_covariance: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
angular_velocity: 
  x: -0.000771123450249
  y: -0.00155919569079
  z: -2.85540590994e-05
angular_velocity_covariance: [1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07, 0.0, 0.0, 0.0, 1.2184696791468346e-07]
linear_acceleration: 
  x: -0.112540595233
  y: -0.150820448995
  z: 9.93523979187
linear_acceleration_covariance: [8.9999999999999985e-08, 0.0, 0.0, 0.0, 8.9999999999999985e-08, 0.0, 0.0, 0.0, 8.9999999999999985e-08]
 ```
