### ISSUE TITLE
Bottom facing camera VGA calibration

### ISSUE THREAD

**Issue by AlexisTM** [intel-aero/meta-intel-aero#379]
Hey, for anybody interested, I calibrated the camera in VGA resolution and got the following result.

Note that the image is cropped from 640x480 to 630x470 because there are noisy lines on the bottom and the right of the image.

```yaml
intel@intel121:~/.ros/camera_info$ cat bottom_cam.yaml 
image_width: 630
image_height: 470
camera_name: bottom_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [438.2900282347895, 0, 309.9239513520057, 0, 437.478036113458, 243.1522441639167, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.01191108089069289, -0.03574512015872127, 0.001286556156209832, -0.001377510078683868, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [436.6864318847656, 0, 308.808685094471, 0, 0, 437.6833801269531, 243.7079792689674, 0, 0, 0, 1, 0]
```
